# Generated by Django 2.2.4 on 2019-08-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='course',
            field=models.CharField(choices=[('GEN', 'General'), ('FOMB', 'Foundations of Modern Biology'), ('CBB', 'Cell Biology and Biochemistry'), ('MLBA', 'Machine Learning for Biomedical Applications'), ('ACB', 'Algorithms in Computational Biology'), ('NB', 'Network Biology'), ('CGAS', 'Computational Gastronomy'), ('IMB', 'Introduction to Mathematical Biology')], default='GEN', max_length=250),
        ),
    ]
