# Generated by Django 2.2.4 on 2019-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_resourcelink_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
